{{/* Make sure all variables are set properly */}}
{{- include "tc.common.loader.init" . }}

{{- $_ := set .Values.persistence "configfile" (include "wireguard.configfile" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "tc.common.loader.apply" . }}
